### ISSUE TITLE
sizeof() operator is not highlighted

### ISSUE THREAD

**Issue by vladimir-didenko** [atom/language-c#151]
sizeof() operator is not highlighted anymore

Test sample

```C
#include "stdio.h"

int main()
{
   printf("sizeof(int) = %zu", sizeof(int));
   return 0;
}
```

**Comment by linquize** [comment]
same in atom 1.10

**Comment by thomasjo** [comment]
The `sizeof` keyword is given the scope `keyword.operator.sizeof.c`, so this is entirely related to syntax themes not giving it a (distinguishable) color. In the case of the default syntax themes One Light and One Dark, `sizeof` is given the color `@mono-1` which is the same as "default text".

In summary, in order to get this resolved, you'll need to open issues on the relevant syntax themes.

/cc @simurai 

---
NOTE: the scope in the grammar hasn't changed since November 2014, and the relevant code in the One syntax themes has not changed since May 2015, so this is not a recent "regression" as far as I can tell.

**Comment by simurai** [comment]
@vladimir-didenko What theme are you using?

Made PRs to highlight operators in C for the One themes. Should be in Atom `1.12`.

**Comment by vladimir-didenko** [comment]
@simurai 

> What theme are you using?

One Dark.

> Made PRs to highlight operators in C for the One themes.

Great. Thanks!
