### ISSUE TITLE
C++14 digit separators are not recognized

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#154]
_From @BillyONeal on July 10, 2016 5:18_
- VSCode Version: 1.3.0
- OS Version: Windows 10 10586

![Broken digit separators demonstration](https://cloud.githubusercontent.com/assets/1544943/16711798/101ddb64-4623-11e6-91e1-74c6bf5d0bc3.png)

_Copied from original issue: Microsoft/vscode#9018_

**Comment by aeschli** [comment]
_From @BillyONeal on July 10, 2016 5:21_

Note: Does not matter whether or not the C++ extension is installed.

**Comment by sean-mcmanus** [comment]
Can someone give a status update on a fix? People are blaming VS Code and the C++ extension when it's not our bug.

**Comment by 50Wliu** [comment]
I'm the only Atom maintainer actively working on languages.  Given that there's around 25 core language packages, it's quite a lot of work.  I rely a lot on people sending PRs.  Regarding language-c, I know that @thomasjo has some plans to improve it, and so does @alpyre.  Onto your questions however:

> Can someone give a status update on a fix?

I am not aware of any Atom maintainer working on this, nor has a PR been submitted.

> Do we need to fix the bug ourselves or is someone else planning to?

While not necessary, it would be appreciated if a PR is submitted.  Otherwise, we'll get around to it eventually, though I can't say when.
