### ISSUE TITLE
Incorrect Syntax highlighting

### ISSUE THREAD

**Issue by shreyanshk** [atom/language-c#202]
### Description

Incorrect syntax highlighting in C language in atom.

### Steps to Reproduce

1. Save a file with code given in additional information and extension ".c":

**Expected behavior:** at position 17:51 Atom should recognizes that string starts from this point and ends at 17:82

**Actual behavior:** Atom doesn't recognize that 17:51 marks the start of a string.

**Reproduces how often:** Always present
### Versions
atom --version:
Atom    : 1.13.1
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0

apm --version:
(node:5033) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
apm  1.15.2
npm  4.1.2
node 7.5.0 x64
python 3.6.0
git 2.11.1

uname -a:
Linux 4.9.6-1-ARCH #1 SMP PREEMPT Thu Jan 26 09:22:26 CET 2017 x86_64 GNU/Linux

Running a completely up to date Arch Linux installation.

### Additional Information

#include <efi.h>
#include <efilib.h>

#include "console.h"
#include "disk.h"
#include "graphics.h"
#include "linux.h"
#include "pefile.h"
#include "util.h"
#include "measure.h"

#ifndef EFI_OS_INDICATIONS_BOOT_TO_FW_UI
#define EFI_OS_INDICATIONS_BOOT_TO_FW_UI 0x0000000000000001ULL
#endif

/* magic string to find in the binary image */
static const char __attribute__((used)) magic[] = "#### LoaderInfo: systemd-boot " VERSION " ####";

static const EFI_GUID global_guid = EFI_GLOBAL_VARIABLE;

enum loader_type {
        LOADER_UNDEFINED,
        LOADER_EFI,
        LOADER_LINUX
};

**Comment by 50Wliu** [comment]
> Electron: 1.4.15

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You may want to subscribe to https://bugs.archlinux.org/task/50357 for updates.
