### ISSUE TITLE
C++ Highlight argument variables inside functions

### ISSUE THREAD

**Issue by AndyBay** [atom/language-c#219]
In Visual studio function arguments differ in colour from
other variables initialized within the function.

This is a great way to differentiate between them.

Visual studio:
![vs_function_arguments_colour](https://cloud.githubusercontent.com/assets/1170184/24578468/2d5674fe-16e1-11e7-90a2-05196e04c7ca.png)

Atom:
![atom_function_arguments_colour](https://cloud.githubusercontent.com/assets/1170184/24578470/375b2b20-16e1-11e7-8a4a-b1ab5c7bacd9.png)

As seen above the variable "newName" has a different coulour compared to "name".

Would this be possible in Atom as well?

**Comment by thomasjo** [comment]
This is not possible with a purely regex-based system like we currently have in Atom. Functionality of this nature requires a parser-based system — essentially we need an AST (abstract syntax tree) to do this in a meaningful way. Once we get [tree-sitter](https://github.com/tree-sitter/tree-sitter) (or some such) implemented in Atom, we can handle this request.

---
@atom/maintainers Since this is not actionable in the immediate future, I propose we close this until we have the necessary bits in place for this to be actionable. Thoughts? :thought_balloon:

**Comment by 50Wliu** [comment]
Sounds good to me.  I didn't read the issue closely enough.
