### ISSUE TITLE
Add an option to remove "std::" from all the snippets

### ISSUE THREAD

**Issue by JatinYadav1307** [atom/language-c#220]
I usually start all my cpp/c files by writing

```cpp
using namespace std;
```

Now after this having every snippet insert ```std::``` in front of everything I use is very unpleasant. Add an option to toggle these if possible.

Thanks

**Comment by thomasjo** [comment]
What you are proposing is not currently supported by the underlying snippet framework. Your best option now is to duplicate the relevant snippets and place them in your `~/.atom/snippets.cson` file, then remove the `std::` prefix. Alternatively you'll have to fork this language package, and publish and maintain that fork as a series of patch commits that removes the namespace prefix.

Since this is not supported by our snippets framework, not likely to be supported in the near future, and combined with the fact viable workarounds exists, I'm closing this issue for the time being. Once the relevant architecture is in place, we can re-open this issue.

---
_Side note: always specifying the full namespace prefix is advisable to ensure your code keeps compiling regardless of changes in other included libraries etc that might cause naming conflicts when references are not fully qualified._
