### ISSUE TITLE
[Question] How to change C++ '%' flag color

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/language-c#225]
I can only change C '%' flag color
Example:

C++
![screen shot 2017-04-09 at 19 22 56](https://cloud.githubusercontent.com/assets/20783502/24836870/fc9fd6dc-1d59-11e7-86f9-e11122db6cad.png)

C
![screen shot 2017-04-09 at 19 22 35](https://cloud.githubusercontent.com/assets/20783502/24836872/006e4280-1d5a-11e7-816c-0a8b109682e7.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by ooJerryLeeoo** [comment]
@50Wliu I think this is a bug, not question...

**Comment by ooJerryLeeoo** [comment]
The `%` flag color should be change by adding this code into style.less:
``` less
.syntax--source.syntax--c,
.syntax--source.syntax--cpp {
  .syntax--constant.syntax--other.syntax--placeholder {
    color: <some color>;
  }
}
```
But it can only change the color when the syntax is `C`.

**Comment by 50Wliu** [comment]
Please create a new issue and completely fill out the issue template.
