### ISSUE TITLE
Syntax highlighting for function calls breaks with line breaks

### ISSUE THREAD

**Issue by detly** [atom/language-c#23]
Breaking the line between a function name and the opening parenthesis of a function call in C is valid syntax, but fails to be correctly highlighted. Adding space is fine though.

![atom_c_highlight](https://cloud.githubusercontent.com/assets/311239/3265622/a0a4048e-f296-11e3-9a77-057eedd163a4.gif)

This is using the _Base 16 Tomorrow Dark_ theme.

**Comment by zeckalpha** [comment]
I had a similar, perhaps related issue with macros in munificent/wren/pull/105:

~~~ C
#define SOME_MACRO (type) \
    type cast_to_##type(arg) { return (type) arg; }

SOME_MACRO(int)  // Highlighting breaks here.
SOME_MACRO(long)
SOME_MACRO(double)
~~~

It looks like GitHub breaks on this, too. Not sure there is a good solution since it would involve the syntax highlighter evaluating cpp to decide what to do.

**Comment by alpyre** [comment]
This is the same issue with #118 and it won't fix as I've explained in there.
You can _close_, _block_ or _label as "won't fix"_ this issue.
Best regards.
