### ISSUE TITLE
Missing highlighting of types

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#243]
From https://github.com/Microsoft/vscode/issues/29292

1.
```
#include <string>

std::string s; // not highlighted
```
2. custom
```
#include <stdint.h>

typedef int8_t   int8;
int8 test; // int8   is not highlighted
```

Built-in types are highlighted though!
What has to be done to get all types highlighted  ?

**Comment by hgdsraj** [comment]
This is normal behaviour. Neither Vim, VS Code, Sublime Text nor Gedit support this behavior. Built in types are highlighted, externally defined types are not. This is logical behaviour as the highlighting of external types would require continuous definition lookup. Perhaps this issue is better served by an external plugin.

**Comment by AeroStun** [comment]
Though, this is a functionnality in Geany

**Comment by maxbrunsfeld** [comment]
This is fixed if you use the new [Tree-sitter](http://tree-sitter.github.io/tree-sitter) parsing system, which is enabled by default in Atom 1.32 Beta. If you're not the beta channel, you can enable it by checking the `Use Tree-sitter Parsers` box in the settings view, or wait for Atom 1.32 Stable to be released. Thanks!
