### ISSUE TITLE
C++: Single open brace in #define

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#280]
_From @CChelak on July 18, 2018 17:45_

In our company's code, we define namespaces as macros. An example is below:
```c++
    #define BEGIN_NAMESPACE_MYCODE namespace mycode {
    #define END_NAMESPACE_MYCODE }
```
I've notice however, that the syntax highlighter doesn't know how to handle the open bracket at the end of the define and the rest of the code becomes highlighted as if it were part of the macro. Oddly enough, the word `namespace` seems to be an equal culprit in this problem because defining something as follows doesn't mess up syntax highlighting:
```c++
    #define BEGIN_DONUT_TIME fried dough {
```
Any thoughts?

_Copied from original issue: Microsoft/vscode#54599_

**Comment by maxbrunsfeld** [comment]
This code displays correctly as long as the Tree-sitter parser is enabled.

**Comment by rsese** [comment]
Thanks Max :+1: and thanks for sharing the report @aeschli - since this problem isn't an issue with Tree-sitter, we'll go ahead and close per the notes below.

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.
