### ISSUE TITLE
proper C and C++ syntax highlighting?

### ISSUE THREAD

**Issue by aeschli** [atom/language-c#281]
_From @Castlespring on July 18, 2018 11:12_

The syntax highlighting for C and C++ is totally off. My `#define` and `#ifdef`/`#ifndef` coloring is wrong and the definition name is colored differently to the #define, `#ifdef` and `#ifndef` which is not nice.

The real bugger is that when I have `Windows.h` included (or any header file containing its own type-definitions), type-definitions like `NTSTATUS`, `BOOLEAN`, `ULONG`, `SIZE_T`, etc. and structures will not be highlighted in a color. Only standard ones like `int`, `bool` will be highlighted.

When using `typedef struct _STRUCTURE_NAME`, only that `STRUCTURE_NAME` will be highlighted, as well. If you did:

```c++
typedef struct _STRUCTURE_NAME {
...
} STRUCTURE_NAME, *PSTRUCTURE_NAME;
```

The `STRUCTURE_NAME` and `PSTRUCTURE_NAME` will not be highlighted in a color.

_Copied from original issue: Microsoft/vscode#54567_

**Comment by ImmortaleVBR** [comment]
This is annoying me as well. I wanted to use Visual Studio Code as an editor for C every now and then, but the syntax highlighting limitation ruins the experience for me; I am used to the highlighting. You cannot work with specific highlighting for 5+ years straight and then just ditch it... it is easier said than done.

**Comment by safield** [comment]
+1.

-Adding template diamond brackets to a method call breaks syntax highlight.
```
SomeFunction(); // highlighted correctly with "Functions" token color
SomeFunction<Foo>(); // loses highlighting and is colored as default foreground.
```


-there is no way to differentiate between a method declaration/definition, and a method invocation in a color theme. This behavior is present in similar editors to VSCode. In the following snippet, both "Foo" strings will be colored the same, where as in Sublime Text, you can theme them separately.

```
void MyClass::Foo()
{
    Foo();
}
```


Class definitions are broken. In the following snippet, everything after the word "class" is defaulted to the same standard foreground color. Expected behavior would be the public keyword receives keyword color and the class declaration receives a unique color as well.

class NameSpace::SomeClass: public NameSpace2::SomeOtherClass
{
};

**Comment by maxbrunsfeld** [comment]
Our new parsing system, [Tree-sitter](http://tree-sitter.github.io/tree-sitter/) allows types to be highlighted consistently (as opposed to just highlighting a fixed list of known types).

Tree-sitter is enabled by default in Atom 1.32 beta. If you're not using our Beta channel, you can opt-in to using Tree-sitter by checking the `Use Tree-sitter Parsers` box in the settings view.

Aside from that, I don't think this will ever be fixed in the older TextMate parser, which I believe is what VSCode is using. I believe this is the expected behavior for that parser.
