### ISSUE TITLE
Wrong scope on new

### ISSUE THREAD

**Issue by chbk** [atom/language-c#292]
`new` is scoped as `entity.name.function.c` when it should be `keyword.control.cpp`.

```c++
  int * foo;
  foo = new (nothrow) int [5];
```

**Comment by Aerijo** [comment]
Is `new` a keyword in C?

**Comment by Ben3eeE** [comment]
In tree-sitter it's `keyword.operator`.

@thomasjo @maxbrunsfeld What do you think `new` and `delete` should be scoped as?

**Comment by maxbrunsfeld** [comment]
I don't have a strong opinion, as long as it's `keyword.`-something, so that it's colored like the other keywords in the built-in themes. `keyword.operator` seems fine to me.

**Comment by Ben3eeE** [comment]
Personally I like `keyword.operator` because I styled `keyword.control` to be italic in my personal stylesheet to get some fancy looking `if`s. But I am fine with whatever 🙂 

I'll wait for @thomasjo to reply. @thomasjo Feel free to close this if you think `keyword.operator` is fine. It's actually `keyword.operator.new/delete` so you should be able to style it as a function or the same as `keyword.control.cpp` if you want.

**Comment by chbk** [comment]
I agree with `keyword.operator.new/delete`, it's specific enough to differentiate from other operators.
