### ISSUE TITLE
Strings in #define's are not highlighted

### ISSUE THREAD

**Issue by sfan5** [atom/language-c#31]
Atom 0.109.0, language-c 0.21.0, Linux
![screenshot - 08 07 2014 - 15 26 02](https://cloud.githubusercontent.com/assets/1042418/3510148/ed5ab748-06a3-11e4-8ab8-f38618d3cab2.png)

**Comment by jplatte** [comment]
Wow, I didn't expect to find an existent bug report for this. I experienced a very similar problem, only that it messed up my whole document because the string which didn't get highlighted had a `(` in it which was then interpreted as being outside the string.

A practical example where all highlighting of text after this bug occurs is messed up:

    Foo foo(getSomeString() + " (" + otherString + ')');

This works without the `+ ')'` too of course, but this is about how I encountered this bug and it seems more likely to exist in some real-world code like this.
