### ISSUE TITLE
C++17 namespace attributes breaks subsequent classification

### ISSUE THREAD

**Issue by alexr00** [atom/language-c#317]
_From @Cre3per on January 8, 2019 15:1_

```cpp
// The first angular bracket is incorrectly recognized by the grammar.
namespace [[deprecated]] S
{
  // "fn" is also incorrectly recognized, but when you remove the [[deprecated]] this is resolved.
  void fn(int i)
  {
  }
}
```

_Copied from original issue: Microsoft/vscode#66215_

**Comment by rsese** [comment]
Thanks for the report!  Unless I'm misunderstanding, this looks like it isn't an issue with Tree-sitter?

![with-tree-sitter](https://github-slack.s3.amazonaws.com/monosnap/test.cpp__worktest-tree-sitter_2019-01-10_19-09-53.png)

Going to go ahead and close as detailed below but let me know if this is also a Tree-sitter issue.

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.
