### ISSUE TITLE
C++ Syntax Highlighting gets confused by apostrophes

### ISSUE THREAD

**Issue by alexr00** [atom/language-c#320]
*Edit by @rsese - also an issue with Tree-sitter*

From @Aerijo:

> Tree sitter also trips on this, it just recovers before the function.

![tree-sitter](https://github-slack.s3.amazonaws.com/monosnap/test.cpp__worktest-tree-sitter_2019-02-01_17-42-22.png)

---

_From @damyanp on January 30, 2019 18:21_

Issue Type: <b>Bug</b>

For example:

```
#error Don't do this
void foo() { }
```

The syntax highlighter thinks that a string starts from the apostrophe betwee the "n" and "t" in "don't" and highlights the rest of the file as a string until it reaches the next single quote.

Visual Studio gets this correct, since the entire line for the preprocessor directive is highlighted separately and it doesn't look for strings inside it.

_Copied from original issue: Microsoft/vscode#67568_

**Comment by alexr00** [comment]
_From @damyanp on January 30, 2019 18:22_

Live screenshot: 
![image](https://user-images.githubusercontent.com/8118402/52003272-e6e5b500-2478-11e9-8f11-db03d5949bd8.png)

**Comment by alexr00** [comment]
After the single quote in the error directive everything is categorized as `string.quoted.singe.c`

**Comment by rsese** [comment]
Thanks for the report!

> After the single quote in the error directive everything is categorized as `string.quoted.single.c`

Looks like this behavior isn't an issue with Tree-sitter?  E.g.:

![with-tree-sitter](https://github-slack.s3.amazonaws.com/monosnap/test.cpp__worktest-tree-sitter_2019-02-01_16-18-20.png)

So going to go ahead and close as detailed below.

---

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Comment by Aerijo** [comment]
@rsese Tree sitter also trips on this, it just recovers before the function.

**Comment by rsese** [comment]
Ahhh thanks @Aerijo, just went straight to the function :smile:

![tree-sitter](https://github-slack.s3.amazonaws.com/monosnap/test.cpp__worktest-tree-sitter_2019-02-01_17-42-22.png)

**Comment by maxbrunsfeld** [comment]
This doesn't affect the Tree-sitter parser anymore.
