### ISSUE TITLE
Experimental Syntaxes Please

### ISSUE THREAD

**Issue by jeff-hykin** [atom/language-c#321]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
It is time consuming for Dev's to review/merge grammar changes.

### Steps to Reproduce
1. Click on the Pull Requests tab
2. Observe the many pull requests that fix various issues in solid ways
3. Observe that some have been there for over a year

**Suggestion Solution:**
Can we create an `c.experimental.cson` and `c++.experimental.cson` where changes are merged much more freely and the community can easily test/use all of the fixes people have pushed. It would outsource the testing problem (meaning less work for reviewers). It would also make it a lot less annoying for users who really really need a fix because one `'` is screwing up the syntax of the entire file (see issue #320 which was solved in 2017 by pull request #251 and is still not merged).

**Comment by rsese** [comment]
Thanks for the feedback @jeff-hykin 👍 

We've been adjusting our review process over time to help with tracking pull requests but there's of course room for improvement.   Personally, I don't know if the suggested workflow would necessarily speed things up in general but I'll go ahead and share your idea with the other maintainers.

And I'll go ahead and close this out since because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.

**Comment by jeff-hykin** [comment]
Thanks for responding quickly! I appreciate it.

You guys might like this solution bit more: rather than experimental files, just create an Atom extension "Experimental C++ Syntax" so that the built-in codebase doesn't get bloated. 

I use VS Code, so for my own personal use I went ahead and made a VS Code extension and merged some of the pull requests myself. ([link](https://github.com/jeff-hykin/cpp-textmate-grammar/blob/master/README.md))
