### ISSUE TITLE
C++ lambda return type parsed as variable name

### ISSUE THREAD

**Issue by ToxicPie** [atom/language-c#342]
### Description

Lambda return type in C++ is parsed as a variable name if the lambda is placed inside a scope.

Example:

![image](https://user-images.githubusercontent.com/24191166/78868710-f8abea80-7a75-11ea-8a8f-d3e871e0d3cb.png)

```cpp
void foo() {
    auto sum = [](int a, int b) -> int {
        return a + b;
    };
}
```

**Comment by lkashef** [comment]
Hey @ToxicPie, thanks for the report!

Could you please fill-in the template (you can copy the template by creating a new issue), the part I am most interested in is the `Expected Behavior` section.

I tried to check the scope for `int a` and it seems to match the `int` in lambada, knowing more about what you think the behavior should be, would be helpful.
